##
## EPITECH PROJECT, 2021
## B-MUL-200-BDX-2-1-myrpg-louis.pavlovsky
## File description:
## Makefile
##

all:
	$(MAKE) -C src/fct_tools/
	$(MAKE) -C src/my_str/

clean :
	$(MAKE) -C src/fct_tools/ clean
	$(MAKE) -C src/my_str/ clean

fclean: clean
	$(MAKE) -C src/fct_tools/ fclean
	$(MAKE) -C src/my_str/ fclean

re: fclean all